### PR TITLE
add android23 check

### PR DESCRIPTION
**Pull request by rejas**
this adds basic android 2.3 check using writing-mode http://caniuse.com/#feat=css-writing-mode

alas this only allows for xor checks (only IE or only Android checks), so points to discuss before a release should be how someone could specify "only ie<9 and android<3" (and if the css-properties are sufficient for that)

### CODE REVIEW

**Comment by alexprg** [comment]
Hi @rejas Thank you so much.
Hopefully we will release soon a version targeting major mobile OS, and will check your pull request.
Give us some time please :+1: 
Cheers

**Comment by rejas** [comment]
Awesome news regarding the mobile OS, of course I will be patient :-)

**Comment by rejas** [comment]
Heyho, any news /timeframe regarding the new version? Been a while now ;-) Cheers, V

**Comment by Kum0ri** [comment]
Hi @rejas . We are scheduling/pointing this release for the beginning of 2017.
Will start with this soon and get back to you when a beta version is available ;)

Cheers!
Daniel.

**Comment by rejas** [comment]
Hi guys (@alexprg @brunoamorim), any news on your roadmap/plans for 2018? Should I update this PR or can I close it due to inactivity of the project?

**Pull request closed without merging**
