### PR TITLE
Create gr.html

### PR DESCRIPTION
**Pull request by pligor**
Greek version of the lang files. Excellent work with this contribution!

### CODE REVIEW

**Comment by alexprg** [comment]
@pligor 
Thank you :) 
We just need the translation of the website, that way the link would be http://outdatedbrowser.com/
Cheers

**Comment by pligor** [comment]
Hello! Before start talking about translation I must confess that I have not made your plugin work yet.

May I ask if the outdated-browser plugin is working out of the box? 
I first tried to follow the steps to integrate it in my own webapp but then nothing worked.

Then I tried to take your demo folder along with the necessary files and upload it on http://george.pligor.com/demo/

Still nothing seems to work
I tried it on an old firefox browser, version 15.0
and also tried it on internet explorer 7, via PlayOnLinux application, in ubuntu
Still nothing worked.
Actually in internet explorer there is this exclamation point with "error on page" at the status bar (bottom left of the window)

Could you help?

(I could make this an issue in the repositoty if necessary)

**Comment by alexprg** [comment]
Hi there,
Just tested your links and is working fine, and the plugin should work out if the box (mind the recommendations I wrote in the instructions)  
http://buro.pt/bExx
http://buro.pt/bEUW

Maybe the old FF you are using for testing supports the property?
Strange... can you give me more info? 
really hope I can help
Cheers

**Comment by pligor** [comment]
Thank you very much for these screenshots. Now it is even more bizarre. But I will try to test in real windows system and get back at you.
As far as firefox is concerned I downloaded this one: 
http://ftp.mozilla.org/pub/mozilla.org/firefox/releases/15.0/linux-x86_64/en-US/
If you try to browse modern websites you are going to find them "destroyed" because of not supporting css3 apparently (as well as one of my own websites: http://pligor.com)
And when I checked with http://george.pligor.com/demo I found that is not working.
You could check it yourself. Thanks for the help

**Pull request merged**
