### PR TITLE
Add Traditional Chinese translation

### PR DESCRIPTION
**Pull request by samsam2310**

### CODE REVIEW

**Comment by alexprg** [comment]
Thank you 
We will keep .tw for Traditional Chinese , even if is not very correct (but if we change now we will have broken links)

**Comment by nchild** [comment]
I think that's because the former readme mentioned: "If you have variations of the same language use URL country code, e.g.: br—brazilian portuguese; us—american english."

**Comment by samsam2310** [comment]
Yes.
And you are using 'cn' for zh-cn, so I think 'tw' for 'zh-tw' is a good idea.

**Comment by alexprg** [comment]
@samsam2310 prefect :) It was the way I was thinking approach that.

**Pull request merged**
