### PR TITLE
Add Traditional Chinese translation

### PR DESCRIPTION
**Pull request by samsam2310**

### CODE REVIEW

**Comment by alexprg** [comment]
Hi there, thank you so much.
How to you write Traditional Chinese? Is before or after 中文 ?
I need that info to put in http://buro.pt/ckzN

**Comment by nchild** [comment]
正體中文
Thanks a lot.

**Comment by samsam2310** [comment]
zh-cn(cn) ->  '簡体中文'(For China)
zh-tw(tw) -> '繁體中文'(For Taiwan)

Thanks :)

**Comment by alexprg** [comment]
@samsam2310 @nchild 
Thank you guys so much , I will change that asap.

**Comment by alexprg** [comment]
Once again thank you.
Is online: http://outdatedbrowser.com/tw
Cheers

**Comment by alexprg** [comment]
@samsam2310 @nchild 
Hi guys we need your opinion. We are planing to change the urls according to ISO 639-1 language code + ISO 3166 country codes, but we know that Chinese has more variations then that! 
What is your advise regarding the current translations we have? I know we can have for instance zh-Hans-CN (Chinese written using the Simplified script as used in mainland China) and many other variations, ie, zh-hans and zh-hant are not universal.
For  what I understood in the translations we got was:
- simplified chinese (zh-hans) was a translation from Taiwan, so we should use zh-tw
- traditional chinease (zh-hant) was a translation from main China, so we should use zh-cn
Our idea is to do something like Drupal, and other communities are doing. http://buro.pt/fKYm.
Using this system it seems easier to add new variants in the future.
What do you think?
For the time being we can always do a redirect if someone types /zh-hans to /zh-cn and /zh-hant to /zh-tw
Thank you a lot

**Comment by alexprg** [comment]
@samsam2310 @nchild
Hi guys we need your opinion. We are planing to change the urls according to ISO 639-1 language code + ISO 3166 country codes, but we know that Chinese has more variations then that!
What is your advise regarding the current translations we have? I know we can have for instance zh-Hans-CN (Chinese written using the Simplified script as used in mainland China) and many other variations, ie, zh-hans and zh-hant are not universal.
For what I understood in the translations we got was:

- Traditional Chinese (zh-hans) was a translation from Taiwan, so we should use zh-tw
- Simplified Chinese (zh-hant) was a translation from main China, so we should use zh-cn

Our idea is to do something like Drupal, and other communities are doing. http://buro.pt/fKYm.
Using this system it seems easier to add new variants in the future.
What do you think?
For the time being we can always do a redirect if someone types /zh-hans to /zh-cn and /zh-hant to /zh-tw

Thank you a lot

**Comment by samsam2310** [comment]
I think use zh-tw and zh-cn is good.
This is what we can get from JS, so users can be redirected to their own language with simple JS code.

**Comment by alexprg** [comment]
@samsam2310 ok thank you so much. :+1: 
soon will do an update
Cheers

**Comment by nchild** [comment]
👍🏼

**Pull request merged**
