### PR TITLE
Empty language file functionality incomplete

### PR DESCRIPTION
**Pull request by mikelittman**
If an empty language file is provided, the default ajaxEnglishDefault HTML is never inserted into the outdated container.

### CODE REVIEW

**Comment by alexprg** [comment]
Hi there,
Thank you :) But if an empty language is provided we used as an option for no Ajax, or am I missing something? :+1:

**Comment by mikelittman** [comment]
Hey!

See the following snippet:

```javascript
//Check AJAX Options: if languagePath == '' > use no Ajax way, html is needed inside <div id="outdated">
if( languagePath === ' ' || languagePath.length == 0 ){
    startStylesAndEvents();
}else{
    grabFile(languagePath);
}
```

If languagePath is an empty string or just a single space, it skips the injection and runs `startStylesAndEvents()`.

The only time the variable `ajaxEnglishDefault` is injected is when the Ajax request fails.

**Comment by alexprg** [comment]
@mikelittman 
nice,  :+1:  Need to test in old browsers and add some more suggestions and then I merge that.
Thanks
PS: did you tested in IE6, for instance?

**Comment by mikelittman** [comment]
@alexprg The lowest environment I've tested on thus far is IE8. I can test in a VM shortly, just working on fixing some problems with our site in IE8 right now. Oh IE how woeful you are.

**Comment by mikelittman** [comment]
@alexprg The plugin works in IE6!

**Comment by alexprg** [comment]
@mikelittman 
ehehe doing all that testing is a pain :-1: But we have to ensure that all work well in sites that really need the plugin.
Now give me some time please, I want to merge your update with some others alterations.
thanks again man ;)

**Comment by mikelittman** [comment]
Hey @alexprg. I was testing the code again and for some reason it wasn't behaving as originally expected. I don't think my changes are what is needed. I'd recommend not merging my changes.

Sorry for any troubles!

**Comment by alexprg** [comment]
@mikelittman 
No problem :+1: With a plugin to support  so many old browsers, something that could be simple, becomes a pain.

**Pull request closed without merging**
